
// Restaurant constants
export const recommendations = [
  {
    id: 1,
    name: "The Forest",
    image: "/images/recomendation-image.png",
    category: "Fine Dining",
    rating: 4.5,
    distance: "2 km away",
    deals: 3,
  },
  {
    id: 2,
    name: "Velvet Room",
    image: "/images/recomendation-image.png",
    category: "Fine Dining",
    rating: 4.2,
    distance: "3 km away",
    deals: 3,
  },
  {
    id: 3,
    name: "Cut n' Cut Halfway",
    image: "/images/recomendation-image.png",
    category: "Fine Dining",
    rating: 4.0,
    distance: "1 km away",
    deals: 3,
  },
];

export const nearbyRestaurants = [
  {
    id: "1",
    name: "Le Bernardin",
    category: "Fine Dining",
    image: "/images/recomendation-image.png",
    distance: "3 km",
    deals: 3,
  },
  {
    id: "2",
    name: "Per Se",
    category: "Fine Dining",
    image: "/images/recomendation-image.png",
    distance: "3 km",
    deals: 3,
  },
  {
    id: "3",
    name: "Jean-Georges",
    category: "Fine Dining",
    image: "/images/recomendation-image.png",
    distance: "3 km",
    deals: 3,
  },
  {
    id: "4",
    name: "Gabriel Kreuther",
    category: "Fine Dining",
    image: "/images/recomendation-image.png",
    distance: "3 km",
    deals: 3,
  },
  {
    id: "5",
    name: "Gabriel Kreuther",
    category: "Fine Dining",
    image: "/images/recomendation-image.png",
    distance: "3 km",
    deals: 3,
  },
];

export const recommendedRestaurants = [
  {
    id: 1,
    name: "The Forest",
    image: "/images/recomendation-image.png",
    category: "Fine Dining",
    rating: 4.5,
    distance: "2 km away",
    deals: 3,
  },
  {
    id: 2,
    name: "Velvet Room",
    image: "/images/recomendation-image.png",
    category: "Fine Dining",
    rating: 4.2,
    distance: "3 km away",
    deals: 3,
  },
  {
    id: 3,
    name: "Cut n' Cut Halfway",
    image: "/images/recomendation-image.png",
    category: "Fine Dining",
    rating: 4.0,
    distance: "1 km away",
    deals: 3,
  },
  {
    id: 4,
    name: "Velvet Room",
    image: "/images/recomendation-image.png",
    category: "Fine Dining",
    rating: 4.2,
    distance: "3 km away",
    deals: 3,
  },
  {
    id: 5,
    name: "Cut n' Cut Halfway",
    image: "/images/recomendation-image.png",
    category: "Fine Dining",
    rating: 4.0,
    distance: "1 km away",
    deals: 3,
  },
];

export const allRestaurants = [
  {
    id: "5",
    name: "Tatiana by Kwame Onwuachi",
    category: "Fine Dining",
    image: "/images/recomendation-image.png",
    distance: "3 km",
    deals: 3,
  },
  {
    id: "6",
    name: "Cote",
    category: "Fine Dining",
    image: "/images/recomendation-image.png",
    distance: "3 km",
    deals: 3,
  },
  {
    id: "7",
    name: "Casa Mono",
    category: "Fine Dining",
    image: "/images/recomendation-image.png",
    distance: "3 km",
    deals: 3,
  },
  {
    id: "8",
    name: "Dirt Candy",
    category: "Fine Dining",
    image: "/images/recomendation-image.png",
    distance: "3 km",
    deals: 3,
  },
  {
    id: "9",
    name: "Eleven Madison Park",
    category: "Fine Dining",
    image: "/images/recomendation-image.png",
    distance: "3 km",
    deals: 3,
  },
  {
    id: "10",
    name: "Carmine's - Times Square",
    category: "Fine Dining",
    image: "/images/recomendation-image.png",
    distance: "3 km",
    deals: 3,
  },
];
